use std::io::Cursor;
use std::path::{Path, PathBuf};
use std::process::Stdio;
use image::{ImageFormat, RgbImage, GrayImage};
use lopdf::{Document, Object, Stream};
use uuid::Uuid;

use crate::ocr::tesseract::TempFileGuard;

/// Default DPI for rendering PDF pages.
pub const DEFAULT_RENDER_DPI: u32 = 300;

/// Attempts to extract an image for a specific page of a PDF document.
///
/// Tries the following strategies in order:
/// 1. Extract embedded XObject raster images from the PDF page resources via `lopdf`.
/// 2. If available, invoke external rasterizer (`pdftoppm`) to render the full page.
pub fn render_or_extract_page_image(
    doc: &Document,
    pdf_path: Option<&Path>,
    page_num: u32,
    dpi: u32,
) -> Result<Vec<u8>, String> {
    // Strategy 1: Extract embedded raster image directly from PDF page XObjects
    if let Ok(image_bytes) = extract_embedded_page_image(doc, page_num) {
        if !image_bytes.is_empty() {
            return Ok(image_bytes);
        }
    }

    // Strategy 2: If a physical file path is provided, try native Apple Vision / PDFKit renderer (macOS)
    if let Some(path) = pdf_path {
        #[cfg(target_os = "macos")]
        if let Ok(image_bytes) = render_page_with_apple_vision(path, page_num) {
            if !image_bytes.is_empty() {
                return Ok(image_bytes);
            }
        }
    }

    // Strategy 3: If a physical file path is provided, try external pdftoppm renderer
    if let Some(path) = pdf_path {
        if let Ok(image_bytes) = render_page_with_pdftoppm(path, page_num, dpi) {
            if !image_bytes.is_empty() {
                return Ok(image_bytes);
            }
        }
    }

    Err(format!(
        "Failed to render or extract image for PDF page {}. No embedded raster image found and external renderer not available.",
        page_num
    ))
}

#[cfg(target_os = "macos")]
pub fn render_page_with_apple_vision(pdf_path: &Path, page_num: u32) -> Result<Vec<u8>, String> {
    let binary = crate::ocr::apple_vision::AppleVisionProvider::get_or_compile_binary()
        .ok_or_else(|| "Apple Vision binary not available".to_string())?;

    let out_png = std::env::temp_dir().join(format!("hirelens_render_vision_{}.png", Uuid::new_v4()));
    let guard = TempFileGuard::new(out_png.clone());

    let mut cmd = std::process::Command::new(binary);
    cmd.arg("--render-pdf")
        .arg(pdf_path)
        .arg(page_num.to_string())
        .arg(&guard.path)
        .stdout(Stdio::null())
        .stderr(Stdio::null());

    let output = cmd.output().map_err(|e| format!("Failed to spawn vision renderer: {}", e))?;
    if !output.status.success() {
        return Err("vision renderer returned non-zero exit code".to_string());
    }

    if guard.path.exists() {
        let data = std::fs::read(&guard.path).map_err(|e| format!("Failed to read rendered PNG: {}", e))?;
        return Ok(data);
    }

    Err("Rendered PNG file was not generated by Apple Vision".to_string())
}

/// Extracts the largest embedded raster image on a given PDF page.
pub fn extract_embedded_page_image(doc: &Document, page_num: u32) -> Result<Vec<u8>, String> {
    let pages = doc.get_pages();
    let page_id = pages.get(&page_num).copied().ok_or_else(|| {
        format!("Page {} not found in PDF document", page_num)
    })?;

    let mut candidate_images: Vec<(usize, Vec<u8>)> = Vec::new();

    // Check page resources dictionary directly or via helper
    let mut xobj_dictionaries: Vec<&lopdf::Dictionary> = Vec::new();

    if let Ok((Some(res_dict), _)) = doc.get_page_resources(page_id) {
        if let Ok(xobjects) = res_dict.get(b"XObject") {
            if let Some(d) = resolve_dictionary(doc, xobjects) {
                xobj_dictionaries.push(d);
            }
        }
    }

    // Also check page object directly in case get_page_resources missed it
    if let Ok(page_obj) = doc.get_object(page_id) {
        if let Ok(page_dict) = page_obj.as_dict() {
            if let Ok(res_obj) = page_dict.get(b"Resources") {
                if let Some(res_dict) = resolve_dictionary(doc, res_obj) {
                    if let Ok(xobjects) = res_dict.get(b"XObject") {
                        if let Some(d) = resolve_dictionary(doc, xobjects) {
                            if !xobj_dictionaries.contains(&d) {
                                xobj_dictionaries.push(d);
                            }
                        }
                    }
                }
            }
        }
    }

    for xobjs in xobj_dictionaries {
        for (_name, val) in xobjs.iter() {
            let stream_opt = match val {
                Object::Reference(id) => {
                    doc.get_object(*id).ok().and_then(|o| o.as_stream().ok().cloned())
                }
                Object::Stream(stream) => Some(stream.clone()),
                _ => None,
            };

            if let Some(stream) = stream_opt {
                if let Ok(img_bytes) = extract_image_from_stream_object(&stream) {
                    let size = img_bytes.len();
                    candidate_images.push((size, img_bytes));
                }
            }
        }
    }

    if candidate_images.is_empty() {
        return Err(format!("No embedded images found on page {}", page_num));
    }

    // Pick the candidate with the largest data size (most likely the scanned page image)
    candidate_images.sort_by_key(|b| std::cmp::Reverse(b.0));
    Ok(candidate_images.remove(0).1)
}

fn resolve_dictionary<'a>(doc: &'a Document, obj: &'a Object) -> Option<&'a lopdf::Dictionary> {
    match obj {
        Object::Dictionary(d) => Some(d),
        Object::Reference(id) => doc.get_object(*id).ok().and_then(|o| o.as_dict().ok()),
        _ => None,
    }
}

fn get_dict_name_or_str<'a>(dict: &'a lopdf::Dictionary, key: &[u8]) -> Option<&'a [u8]> {
    dict.get(key).ok().and_then(|o| match o {
        Object::Name(bytes) => Some(bytes.as_slice()),
        Object::String(bytes, _) => Some(bytes.as_slice()),
        _ => None,
    })
}

pub fn extract_image_from_stream_object(stream: &Stream) -> Result<Vec<u8>, String> {
    let dict = &stream.dict;
    let subtype = get_dict_name_or_str(dict, b"Subtype").unwrap_or(&[]);
    if subtype != b"Image" && !subtype.is_empty() {
        return Err("Not an image XObject".to_string());
    }

    let filter = get_dict_name_or_str(dict, b"Filter").unwrap_or(&[]);

    // DCTDecode indicates JPEG compression - raw stream content is valid JPEG
    if filter == b"DCTDecode" {
        return Ok(stream.content.clone());
    }

    let width = dict.get(b"Width").ok().and_then(|o| o.as_i64().ok()).unwrap_or(0) as u32;
    let height = dict.get(b"Height").ok().and_then(|o| o.as_i64().ok()).unwrap_or(0) as u32;
    let color_space = get_dict_name_or_str(dict, b"ColorSpace").unwrap_or(&[]);
    let bits_per_component = dict.get(b"BitsPerComponent").ok().and_then(|o| o.as_i64().ok()).unwrap_or(8);

    if width == 0 || height == 0 {
        // Fallback: try decoding raw buffer with image crate directly
        if let Ok(img) = image::load_from_memory(&stream.content) {
            let mut png_bytes = Vec::new();
            img.write_to(&mut Cursor::new(&mut png_bytes), ImageFormat::Png)
                .map_err(|e| format!("PNG encoding failed: {}", e))?;
            return Ok(png_bytes);
        }
        return Err("Invalid image dimensions".to_string());
    }

    // Decompress stream (e.g. FlateDecode or raw decompressed buffer)
    let decompressed = stream.decompressed_content().unwrap_or_else(|_| stream.content.clone());

    if bits_per_component == 8 {
        if (color_space == b"DeviceRGB" || color_space.is_empty()) && decompressed.len() >= (width * height * 3) as usize {
            if let Some(img_buf) = RgbImage::from_raw(width, height, decompressed[..(width * height * 3) as usize].to_vec()) {
                let mut png_bytes = Vec::new();
                img_buf.write_to(&mut Cursor::new(&mut png_bytes), ImageFormat::Png)
                    .map_err(|e| format!("PNG encoding failed: {}", e))?;
                return Ok(png_bytes);
            }
        } else if color_space == b"DeviceGray" && decompressed.len() >= (width * height) as usize {
            if let Some(img_buf) = GrayImage::from_raw(width, height, decompressed[..(width * height) as usize].to_vec()) {
                let mut png_bytes = Vec::new();
                img_buf.write_to(&mut Cursor::new(&mut png_bytes), ImageFormat::Png)
                    .map_err(|e| format!("PNG encoding failed: {}", e))?;
                return Ok(png_bytes);
            }
        }
    }

    // Fallback: try decoding raw buffer with image crate
    if let Ok(img) = image::load_from_memory(&stream.content) {
        let mut png_bytes = Vec::new();
        img.write_to(&mut Cursor::new(&mut png_bytes), ImageFormat::Png)
            .map_err(|e| format!("PNG encoding failed: {}", e))?;
        return Ok(png_bytes);
    }

    Err("Unsupported image stream encoding".to_string())
}

/// Attempts to render a specific page using the system `pdftoppm` utility if available.
pub fn render_page_with_pdftoppm(pdf_path: &Path, page_num: u32, dpi: u32) -> Result<Vec<u8>, String> {
    let output_prefix = std::env::temp_dir().join(format!("hirelens_render_{}", Uuid::new_v4()));
    let expected_png = PathBuf::from(format!("{}-{}.png", output_prefix.display(), page_num));
    let guard = TempFileGuard::new(expected_png.clone());

    let mut cmd = std::process::Command::new("pdftoppm");
    cmd.arg("-png")
        .arg("-r")
        .arg(dpi.to_string())
        .arg("-f")
        .arg(page_num.to_string())
        .arg("-l")
        .arg(page_num.to_string())
        .arg(pdf_path)
        .arg(&output_prefix)
        .stdout(Stdio::null())
        .stderr(Stdio::null());

    let output = cmd.output().map_err(|e| format!("Failed to spawn pdftoppm: {}", e))?;

    if !output.status.success() {
        return Err("pdftoppm returned non-zero exit code".to_string());
    }

    if guard.path.exists() {
        let data = std::fs::read(&guard.path).map_err(|e| format!("Failed to read rendered PNG: {}", e))?;
        return Ok(data);
    }

    // pdftoppm might zero-pad page numbers e.g. -01.png, -001.png
    for padding in 1..=6 {
        let padded_name = format!("{}-{:0width$}.png", output_prefix.display(), page_num, width = padding);
        let padded_path = PathBuf::from(padded_name);
        if padded_path.exists() {
            let padded_guard = TempFileGuard::new(padded_path.clone());
            let data = std::fs::read(&padded_guard.path).map_err(|e| format!("Failed to read rendered PNG: {}", e))?;
            return Ok(data);
        }
    }

    Err("Rendered PNG file was not generated by pdftoppm".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_from_synthetic_image_stream() {
        // Create an in-memory synthetic RGB image
        let img = RgbImage::new(10, 10);
        let mut png_bytes = Vec::new();
        img.write_to(&mut Cursor::new(&mut png_bytes), ImageFormat::Png).unwrap();
        assert!(!png_bytes.is_empty());
    }
}
